name: set-filename-to-env.yaml

on: workflow_dispatch

env:
  TEST_WORKFLOW_FILENAME: set-filename-to-env.yaml

jobs:
  get-filename:
    runs-on: ubuntu-latest

    steps:
    - name: Display workflow filename
      run: echo "Workflow filename is $TEST_WORKFLOW_FILENAME"
