name: test linux command

on:
  push:

jobs:
  build:
    runs-on ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: start linux command
      run:
        echo "start linux command"
        ls